### ISSUE TITLE
pmdl not supported on Android?

### ISSUE THREAD

**Issue by Durgesh92** [seasalt-ai/snowboy#18]
I have replaced alexa.umdl from the Android demo with the pmdl model and facing a crash now.

E/libc: Access denied finding property "ro.vendor.df.effect.conflict"
E/Perf: Fail to get file list ai.kitt.snowboy.demo
    getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
    Fail to get file list ai.kitt.snowboy.demo
    getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array

A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13983 (tt.snowboy.demo), pid 13983 (tt.snowboy.demo)

**Comment by Hemanshu-Bhargav** [comment]
Hi @Durgesh92, did you close this issue because you found a solution?

**Comment by sveinbjornt** [comment]
FWIW, I've got a pmdl working just fine on Android in a project I'm currently developing.

**Comment by Hemanshu-Bhargav** [comment]
Hi @sveinbjornt, thanks for letting me know! 
Forgive me, I haven't looked at the code in a very long time, but I received the error in #3— last I checked. 
My plan was to rewrite the classes myself (since the "resources" have not changed). However, I'm getting the impression that the library worked out-of-the-box for you?

**Comment by sveinbjornt** [comment]
Yeah, I built the JNI files via Swig, with the 64-bit flag as outlined in the following instructions.

https://github.com/seasalt-ai/snowboy/tree/master/examples/Android

To see a more or less working example in Java (I apologize for the clumsy code, not a Java guy), you can take a look at:

https://github.com/mideind/flutter_snowboy

I'm literally working on this right now, so this is still very much a work in progress, but yes, getting Snowboy to run on Android is possible w. the current state of the project.

**Comment by Hemanshu-Bhargav** [comment]
Thanks so much! I'll check it out
